### PR TITLE
show `COV2-2165` in escape selections

### PR DESCRIPTION
**Pull request by jbloom**
@tylernstarr @agreaney, this just updates the escape-selection plots to show COV2-2165 as in newest Figure 6. Can one of you review and merge?

### CODE REVIEW

**Comment by ajgreaney** [comment]
@jbloom I think the color for single-nt accessible mutations is still green here. The code still says this:
`scale_color_manual(values=[CBPALETTE[0], CBPALETTE[3], CBPALETTE[6]]) +`

To make this plot:
image

I'm pretty sure `CBPALETTE[3]` is actually green, not blue (which is `CBPALETTE[5]`). But as the only one of us 3 with normal color vision, @jbloom I think you would have to confirm. The other test would be if @tylernstarr can't see the green dots well...

**Comment by jbloom** [comment]
@ajgreaney, yes I changed it from blue back to green. The rationale being that the actual figure also uses the orange-light blue-dark blue RBD coloring scheme, so I felt it got too confusing to have the points also be blue in the figure. (Not a problem for Figure 3, neut assays, as they don't use RBD coloring scheme).

So I think the main question here would just be can you and @tylernstarr tell the green circles apart from the red diamonds and the gray x characters. If so, then this color scheme is probably OK. 

We could also do something other than green, but I couldn't think of anything else distinct from red that didn't start to look very similar to some of the other color scales used elsewhere (like the orange - blue domain, or the yellow-brown coloring of logo plots by DMS).

I'm hoping with both shapes and colors, it will work for everyone?

**Comment by ajgreaney** [comment]
I think red and green together might be too blatant a violation of good color choices, even with the different shapes. What about wine (#882255) and teal (#44AA99), from this [`muted` color palette](https://personal.sron.nl/~pault/#sec:qualitative), as used in Figure 5C?

**Comment by ajgreaney** [comment]
But if you strongly prefer to leave it as-is, or it is too much trouble to remake the figure @jbloom then I defer to you.

**Comment by jbloom** [comment]
@tylernstarr, do you prefer colors above? Are they better for your color-blindness too? If so, I can re-make with those.

**Comment by tylernstarr** [comment]
Though the shape diifferentiatiion does help, I do honestly struggle to distinguish the green and the gray quite badly. I do think the pop of the orange/red diamonds is important to keep though, so I don't necessarily favor the other combo as we want that diamond to stand out. So, my vote would probably still be the blue points, or keep the green as it is distinguishable enough where I can at least see if I look carefully

**Comment by jbloom** [comment]
OK, in this case I think we should keep as is. I agree that it's nice to have the diamonds pop out, which I think the current red does better.

I'm open to changing the green circles to a different color, but I don't think it should be blue because the figure is also using blue (even in that same panel with antibody names) to mean something else. So maybe we should just keep as is unless we can come up with a better substitute for green?

**Comment by tylernstarr** [comment]
fine with me

**Review by tylernstarr — APPROVED** [review]
approve but will leave allie to merge if she has final thoughts on color

**Comment by jbloom** [comment]
I'm going to go ahead and merge myself just so we don't get conflicted pull requests. @ajgreaney, still happy to update colors if we can find something that fixes all of above, but seems like relatively minor issue so maybe let's keep this conversation open but wrap up other stuff so we can send to co-authors while we think about color scheme for this panel.

**Comment by ajgreaney** [comment]
Ok to circle back to colors, now that other things have been wrapped up, what about replacing the green with "dark yellow" `#666633`, "dark red" `#663333`, or "olive" `#999933` - whichever of these allows Tyler to see this color as distinct from the gray, while still allowing the orange-red (`#D55E00`) of the escape mutations to pop. 

Colors taken from [here](https://personal.sron.nl/~pault/#sec:qualitative).
And I examined them side-by-side with the orange-red [here](https://learnui.design/tools/data-color-picker.html#palette).

**Comment by jbloom** [comment]
OK, @ajgreaney and @tylernstarr: I have tried all three of the additional colors that @ajgreaney suggested above along with the original green for the mutation escape figure. Here are the images:

dark_yellow
dark_red
olive
cbpalette_green

To me as a *non* color blind person, the last one (the green, currently in the paper) is by far the clearest in terms of distinction of the three categories. But if one of the others is way better for your color-blind views, let me know and we can use that instead.

**Comment by ajgreaney** [comment]
Wow, despite my efforts and suggestions, everything except the cbPalette green and purple (aka dark red) looks gray. The Christmas tree red/green feels very wrong and disturbing to me, but I think I'm going to throw in the towel and say whatever you and Tyler want is fine with me.

**Comment by jbloom** [comment]
I think part of it may be that I have alpha at about 0.4 or 0.45 for the single-nucleotide points, as otherwise they overlap in an indistinguishable way. But I think that fades all non-bright colors to gray.

**Pull request merged**
